name: Run Tests & Generate Allure Report

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest
        playwright install chromium
    
    - name: Run D365 tests with Allure (with screenshots & videos)
      env:
        D365_USERNAME: ${{ secrets.D365_USERNAME }}
        D365_PASSWORD: ${{ secrets.D365_PASSWORD }}
        HEADED: false
        PWDEBUG: 0
      run: |
        # Run tests and generate allure results with screenshots
        pytest tests/d365/test_d365_sales_order.py -v \
          --alluredir=allure-results \
          --screenshot=on \
          --video=retain-on-failure \
          --tracing=retain-on-failure
      continue-on-error: true
    
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_report: allure-report
        gh_pages: gh-pages
        allure_history: allure-history
    
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        keep_files: false
