name: BrowserStack Tests

on:
  # Manual trigger
  workflow_dispatch:
  
  # Scheduled trigger (every day at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install chromium
    
    - name: Setup BrowserStack environment
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    
    - name: Run tests on BrowserStack
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        D365_USERNAME: ${{ secrets.D365_USERNAME }}
        D365_PASSWORD: ${{ secrets.D365_PASSWORD }}
        HEADED: false
      run: |
        pytest tests/d365/test_d365_sales_order.py::test_d365_login_page_loads -v
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          reports/
        if-no-files-found: ignore
