name: Deploy Landing Page

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'index.html'

jobs:
  deploy-landing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: gh-pages
    
    - name: Copy index.html from main
      run: |
        git fetch origin main
        git checkout origin/main -- index.html
    
    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add index.html
        git commit -m "Update landing page" || echo "No changes to commit"
        git push origin gh-pages
