name: Smoke Tests (Quick)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium
    
    - name: Run smoke tests locally (no BrowserStack)
      env:
        D365_USERNAME: ${{ secrets.D365_USERNAME }}
        D365_PASSWORD: ${{ secrets.D365_PASSWORD }}
        HEADED: false
      run: |
        pytest tests/d365/test_d365_sales_order.py::test_d365_login_page_loads -v
    
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: smoke-test-results
        path: |
          test-results/
          reports/
        if-no-files-found: ignore
